/* Sorting networks generated file */
/* This file is generated - do not edit manually */

#include <stdlib.h> /* For malloc/free in merge function */

/* Branchless swap macro using temporary variable */
#define SWAP(x, y)                      \
  do                                    \
  {                                     \
    double tmp = (x) < (y) ? (x) : (y); \
    (y) = (x) > (y) ? (x) : (y);        \
    (x) = tmp;                          \
  } while (0)

/* Sorting network for 3 elements - 3 comparators */
static inline void sort3(double *d)
{
  SWAP(d[0], d[1]);
  SWAP(d[0], d[2]);
  SWAP(d[1], d[2]);
}

/* Sorting network for 4 elements - 5 comparators */
static inline void sort4(double *d)
{
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[1], d[2]);
}

/* Sorting network for 9 elements - 25 comparators */
static inline void sort9(double *d)
{
  /* Stage 1: Sort columns */
  SWAP(d[0], d[1]);
  SWAP(d[3], d[4]);
  SWAP(d[6], d[7]);
  SWAP(d[1], d[2]);
  SWAP(d[4], d[5]);
  SWAP(d[7], d[8]);
  SWAP(d[0], d[1]);
  SWAP(d[3], d[4]);
  SWAP(d[6], d[7]);
  /* Stage 2: Sort rows */
  SWAP(d[0], d[3]);
  SWAP(d[3], d[6]);
  SWAP(d[0], d[3]);
  /* Stage 3: Merge */
  SWAP(d[1], d[4]);
  SWAP(d[4], d[7]);
  SWAP(d[1], d[4]);
  SWAP(d[2], d[5]);
  SWAP(d[5], d[8]);
  SWAP(d[2], d[5]);
  SWAP(d[1], d[3]);
  SWAP(d[5], d[7]);
  SWAP(d[2], d[6]);
  SWAP(d[4], d[6]);
  SWAP(d[2], d[4]);
  SWAP(d[2], d[3]);
  SWAP(d[5], d[6]);
}

// Auto-generated sorting networks
// Generated by generate_sorting_networks.py

/* Sorting network for 5 elements - 9 comparators */
static inline void sort5(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[3]);
  SWAP(d[1], d[4]);

  /* Stage 2 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);

  /* Stage 3 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[4]);

  /* Stage 4 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[4]);

  /* Stage 5 */
  SWAP(d[2], d[3]);
}

/* Sorting network for 6 elements - 12 comparators */
static inline void sort6(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[5]);
  SWAP(d[1], d[3]);
  SWAP(d[2], d[4]);

  /* Stage 2 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[4]);

  /* Stage 3 */
  SWAP(d[0], d[3]);
  SWAP(d[2], d[5]);

  /* Stage 4 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);

  /* Stage 5 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[4]);
}

/* Sorting network for 7 elements - 16 comparators */
static inline void sort7(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[6]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);

  /* Stage 2 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[4]);
  SWAP(d[3], d[6]);

  /* Stage 3 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[5]);
  SWAP(d[3], d[4]);

  /* Stage 4 */
  SWAP(d[1], d[2]);
  SWAP(d[4], d[6]);

  /* Stage 5 */
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);

  /* Stage 6 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
}

/* Sorting network for 8 elements - 19 comparators */
static inline void sort8(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);

  /* Stage 2 */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[5]);
  SWAP(d[2], d[6]);
  SWAP(d[3], d[7]);

  /* Stage 3 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);

  /* Stage 4 */
  SWAP(d[2], d[4]);
  SWAP(d[3], d[5]);

  /* Stage 5 */
  SWAP(d[1], d[4]);
  SWAP(d[3], d[6]);

  /* Stage 6 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
}

/* Sorting network for 10 elements - 29 comparators */
static inline void sort10(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[8]);
  SWAP(d[1], d[9]);
  SWAP(d[2], d[7]);
  SWAP(d[3], d[5]);
  SWAP(d[4], d[6]);

  /* Stage 2 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[4]);
  SWAP(d[5], d[8]);
  SWAP(d[7], d[9]);

  /* Stage 3 */
  SWAP(d[0], d[3]);
  SWAP(d[2], d[4]);
  SWAP(d[5], d[7]);
  SWAP(d[6], d[9]);

  /* Stage 4 */
  SWAP(d[0], d[1]);
  SWAP(d[3], d[6]);
  SWAP(d[8], d[9]);

  /* Stage 5 */
  SWAP(d[1], d[5]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[8]);
  SWAP(d[6], d[7]);

  /* Stage 6 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[5]);
  SWAP(d[4], d[6]);
  SWAP(d[7], d[8]);

  /* Stage 7 */
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);

  /* Stage 8 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
}

/* Sorting network for 11 elements - 35 comparators */
static inline void sort11(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[9]);
  SWAP(d[1], d[6]);
  SWAP(d[2], d[4]);
  SWAP(d[3], d[7]);
  SWAP(d[5], d[8]);

  /* Stage 2 */
  SWAP(d[0], d[1]);
  SWAP(d[3], d[5]);
  SWAP(d[4], d[10]);
  SWAP(d[6], d[9]);
  SWAP(d[7], d[8]);

  /* Stage 3 */
  SWAP(d[1], d[3]);
  SWAP(d[2], d[5]);
  SWAP(d[4], d[7]);
  SWAP(d[8], d[10]);

  /* Stage 4 */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[2]);
  SWAP(d[3], d[7]);
  SWAP(d[5], d[9]);
  SWAP(d[6], d[8]);

  /* Stage 5 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[6]);
  SWAP(d[4], d[5]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);

  /* Stage 6 */
  SWAP(d[2], d[4]);
  SWAP(d[3], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[9]);

  /* Stage 7 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);

  /* Stage 8 */
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
}

/* Sorting network for 12 elements - 39 comparators */
static inline void sort12(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[8]);
  SWAP(d[1], d[7]);
  SWAP(d[2], d[6]);
  SWAP(d[3], d[11]);
  SWAP(d[4], d[10]);
  SWAP(d[5], d[9]);

  /* Stage 2 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[5]);
  SWAP(d[3], d[4]);
  SWAP(d[6], d[9]);
  SWAP(d[7], d[8]);
  SWAP(d[10], d[11]);

  /* Stage 3 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[6]);
  SWAP(d[5], d[10]);
  SWAP(d[9], d[11]);

  /* Stage 4 */
  SWAP(d[0], d[3]);
  SWAP(d[1], d[2]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[11]);
  SWAP(d[9], d[10]);

  /* Stage 5 */
  SWAP(d[1], d[4]);
  SWAP(d[3], d[5]);
  SWAP(d[6], d[8]);
  SWAP(d[7], d[10]);

  /* Stage 6 */
  SWAP(d[1], d[3]);
  SWAP(d[2], d[5]);
  SWAP(d[6], d[9]);
  SWAP(d[8], d[10]);

  /* Stage 7 */
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);

  /* Stage 8 */
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);

  /* Stage 9 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
}

/* Sorting network for 13 elements - 45 comparators */
static inline void sort13(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[12]);
  SWAP(d[1], d[10]);
  SWAP(d[2], d[9]);
  SWAP(d[3], d[7]);
  SWAP(d[5], d[11]);
  SWAP(d[6], d[8]);

  /* Stage 2 */
  SWAP(d[1], d[6]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[11]);
  SWAP(d[7], d[9]);
  SWAP(d[8], d[10]);

  /* Stage 3 */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[2]);
  SWAP(d[3], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);

  /* Stage 4 */
  SWAP(d[4], d[6]);
  SWAP(d[5], d[9]);
  SWAP(d[8], d[11]);
  SWAP(d[10], d[12]);

  /* Stage 5 */
  SWAP(d[0], d[5]);
  SWAP(d[3], d[8]);
  SWAP(d[4], d[7]);
  SWAP(d[6], d[11]);
  SWAP(d[9], d[10]);

  /* Stage 6 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[5]);
  SWAP(d[6], d[9]);
  SWAP(d[7], d[8]);
  SWAP(d[10], d[11]);

  /* Stage 7 */
  SWAP(d[1], d[3]);
  SWAP(d[2], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[9], d[10]);

  /* Stage 8 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[4]);
  SWAP(d[5], d[7]);
  SWAP(d[6], d[8]);

  /* Stage 9 */
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);

  /* Stage 10 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
}

/* Sorting network for 14 elements - 51 comparators */
static inline void sort14(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);

  /* Stage 2 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[8]);
  SWAP(d[5], d[9]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[13]);

  /* Stage 3 */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[2]);
  SWAP(d[3], d[7]);
  SWAP(d[5], d[8]);
  SWAP(d[6], d[10]);
  SWAP(d[9], d[13]);
  SWAP(d[11], d[12]);

  /* Stage 4 */
  SWAP(d[0], d[6]);
  SWAP(d[1], d[5]);
  SWAP(d[3], d[9]);
  SWAP(d[4], d[10]);
  SWAP(d[7], d[13]);
  SWAP(d[8], d[12]);

  /* Stage 5 */
  SWAP(d[2], d[10]);
  SWAP(d[3], d[11]);
  SWAP(d[4], d[6]);
  SWAP(d[7], d[9]);

  /* Stage 6 */
  SWAP(d[1], d[3]);
  SWAP(d[2], d[8]);
  SWAP(d[5], d[11]);
  SWAP(d[6], d[7]);
  SWAP(d[10], d[12]);

  /* Stage 7 */
  SWAP(d[1], d[4]);
  SWAP(d[2], d[6]);
  SWAP(d[3], d[5]);
  SWAP(d[7], d[11]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[12]);

  /* Stage 8 */
  SWAP(d[2], d[4]);
  SWAP(d[3], d[6]);
  SWAP(d[5], d[8]);
  SWAP(d[7], d[10]);
  SWAP(d[9], d[11]);

  /* Stage 9 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);

  /* Stage 10 */
  SWAP(d[6], d[7]);
}

/* Sorting network for 15 elements - 56 comparators */
static inline void sort15(double *d)
{
  /* Stage 1 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[10]);
  SWAP(d[4], d[14]);
  SWAP(d[5], d[8]);
  SWAP(d[6], d[13]);
  SWAP(d[7], d[12]);
  SWAP(d[9], d[11]);

  /* Stage 2 */
  SWAP(d[0], d[14]);
  SWAP(d[1], d[5]);
  SWAP(d[2], d[8]);
  SWAP(d[3], d[7]);
  SWAP(d[6], d[9]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[13]);

  /* Stage 3 */
  SWAP(d[0], d[7]);
  SWAP(d[1], d[6]);
  SWAP(d[2], d[9]);
  SWAP(d[4], d[10]);
  SWAP(d[5], d[11]);
  SWAP(d[8], d[13]);
  SWAP(d[12], d[14]);

  /* Stage 4 */
  SWAP(d[0], d[6]);
  SWAP(d[2], d[4]);
  SWAP(d[3], d[5]);
  SWAP(d[7], d[11]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[12]);
  SWAP(d[13], d[14]);

  /* Stage 5 */
  SWAP(d[0], d[3]);
  SWAP(d[1], d[2]);
  SWAP(d[4], d[7]);
  SWAP(d[5], d[9]);
  SWAP(d[6], d[8]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);

  /* Stage 6 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[7], d[9]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[13]);

  /* Stage 7 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[5]);
  SWAP(d[8], d[10]);
  SWAP(d[11], d[12]);

  /* Stage 8 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);

  /* Stage 9 */
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);

  /* Stage 10 */
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
}

/* Sorting network for 16 elements - 60 comparators */
static inline void sort16(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[13]);
  SWAP(d[1], d[12]);
  SWAP(d[2], d[15]);
  SWAP(d[3], d[14]);
  SWAP(d[4], d[8]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[11]);
  SWAP(d[9], d[10]);

  /* Stage 2 */
  SWAP(d[0], d[5]);
  SWAP(d[1], d[7]);
  SWAP(d[2], d[9]);
  SWAP(d[3], d[4]);
  SWAP(d[6], d[13]);
  SWAP(d[8], d[14]);
  SWAP(d[10], d[15]);
  SWAP(d[11], d[12]);

  /* Stage 3 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[8]);
  SWAP(d[7], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);

  /* Stage 4 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[10]);
  SWAP(d[5], d[11]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[12], d[14]);
  SWAP(d[13], d[15]);

  /* Stage 5 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[12]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[13], d[14]);

  /* Stage 6 */
  SWAP(d[1], d[4]);
  SWAP(d[2], d[6]);
  SWAP(d[5], d[8]);
  SWAP(d[7], d[10]);
  SWAP(d[9], d[13]);
  SWAP(d[11], d[14]);

  /* Stage 7 */
  SWAP(d[2], d[4]);
  SWAP(d[3], d[6]);
  SWAP(d[9], d[12]);
  SWAP(d[11], d[13]);

  /* Stage 8 */
  SWAP(d[3], d[5]);
  SWAP(d[6], d[8]);
  SWAP(d[7], d[9]);
  SWAP(d[10], d[12]);

  /* Stage 9 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);

  /* Stage 10 */
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
}

/* Sorting network for 17 elements - 71 comparators */
static inline void sort17(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[11]);
  SWAP(d[1], d[15]);
  SWAP(d[2], d[10]);
  SWAP(d[3], d[5]);
  SWAP(d[4], d[6]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[16]);
  SWAP(d[13], d[14]);

  /* Stage 2 */
  SWAP(d[0], d[6]);
  SWAP(d[1], d[13]);
  SWAP(d[2], d[8]);
  SWAP(d[4], d[14]);
  SWAP(d[5], d[15]);
  SWAP(d[7], d[11]);

  /* Stage 3 */
  SWAP(d[0], d[8]);
  SWAP(d[3], d[7]);
  SWAP(d[4], d[9]);
  SWAP(d[6], d[16]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[14]);

  /* Stage 4 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[13]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[14]);
  SWAP(d[15], d[16]);

  /* Stage 5 */
  SWAP(d[0], d[3]);
  SWAP(d[2], d[5]);
  SWAP(d[6], d[11]);
  SWAP(d[7], d[10]);
  SWAP(d[9], d[13]);
  SWAP(d[12], d[15]);
  SWAP(d[14], d[16]);

  /* Stage 6 */
  SWAP(d[0], d[1]);
  SWAP(d[3], d[4]);
  SWAP(d[5], d[10]);
  SWAP(d[6], d[9]);
  SWAP(d[7], d[8]);
  SWAP(d[11], d[15]);
  SWAP(d[13], d[14]);

  /* Stage 7 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[7]);
  SWAP(d[4], d[8]);
  SWAP(d[6], d[12]);
  SWAP(d[11], d[13]);
  SWAP(d[14], d[15]);

  /* Stage 8 */
  SWAP(d[1], d[3]);
  SWAP(d[2], d[7]);
  SWAP(d[4], d[5]);
  SWAP(d[9], d[11]);
  SWAP(d[10], d[12]);
  SWAP(d[13], d[14]);

  /* Stage 9 */
  SWAP(d[2], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[10]);

  /* Stage 10 */
  SWAP(d[3], d[4]);
  SWAP(d[6], d[8]);
  SWAP(d[7], d[9]);
  SWAP(d[10], d[12]);

  /* Stage 11 */
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);

  /* Stage 12 */
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
}

/* Sorting network for 18 elements - 77 comparators */
static inline void sort18(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);

  /* Stage 2 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[12]);
  SWAP(d[5], d[13]);
  SWAP(d[6], d[8]);
  SWAP(d[9], d[11]);
  SWAP(d[14], d[16]);
  SWAP(d[15], d[17]);

  /* Stage 3 */
  SWAP(d[0], d[14]);
  SWAP(d[1], d[16]);
  SWAP(d[2], d[15]);
  SWAP(d[3], d[17]);

  /* Stage 4 */
  SWAP(d[0], d[6]);
  SWAP(d[1], d[10]);
  SWAP(d[2], d[9]);
  SWAP(d[7], d[16]);
  SWAP(d[8], d[15]);
  SWAP(d[11], d[17]);

  /* Stage 5 */
  SWAP(d[1], d[4]);
  SWAP(d[3], d[9]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[14]);
  SWAP(d[10], d[12]);
  SWAP(d[13], d[16]);

  /* Stage 6 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[5]);
  SWAP(d[3], d[13]);
  SWAP(d[4], d[14]);
  SWAP(d[7], d[9]);
  SWAP(d[8], d[10]);
  SWAP(d[12], d[15]);
  SWAP(d[16], d[17]);

  /* Stage 7 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[5]);
  SWAP(d[4], d[6]);
  SWAP(d[11], d[13]);
  SWAP(d[12], d[14]);
  SWAP(d[15], d[16]);

  /* Stage 8 */
  SWAP(d[4], d[8]);
  SWAP(d[5], d[12]);
  SWAP(d[6], d[10]);
  SWAP(d[7], d[11]);
  SWAP(d[9], d[13]);

  /* Stage 9 */
  SWAP(d[1], d[4]);
  SWAP(d[2], d[8]);
  SWAP(d[3], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[9], d[15]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[14]);
  SWAP(d[13], d[16]);

  /* Stage 10 */
  SWAP(d[2], d[4]);
  SWAP(d[5], d[8]);
  SWAP(d[6], d[10]);
  SWAP(d[7], d[11]);
  SWAP(d[9], d[12]);
  SWAP(d[13], d[15]);

  /* Stage 11 */
  SWAP(d[3], d[5]);
  SWAP(d[6], d[8]);
  SWAP(d[7], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[12], d[14]);

  /* Stage 12 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
}

/* Sorting network for 19 elements - 85 comparators */
static inline void sort19(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[12]);
  SWAP(d[1], d[4]);
  SWAP(d[2], d[8]);
  SWAP(d[3], d[5]);
  SWAP(d[6], d[17]);
  SWAP(d[7], d[11]);
  SWAP(d[9], d[14]);
  SWAP(d[10], d[13]);
  SWAP(d[15], d[16]);

  /* Stage 2 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[7]);
  SWAP(d[3], d[6]);
  SWAP(d[4], d[11]);
  SWAP(d[5], d[17]);
  SWAP(d[8], d[12]);
  SWAP(d[10], d[15]);
  SWAP(d[13], d[16]);
  SWAP(d[14], d[18]);

  /* Stage 3 */
  SWAP(d[3], d[10]);
  SWAP(d[4], d[14]);
  SWAP(d[5], d[15]);
  SWAP(d[6], d[13]);
  SWAP(d[7], d[9]);
  SWAP(d[11], d[17]);
  SWAP(d[16], d[18]);

  /* Stage 4 */
  SWAP(d[0], d[7]);
  SWAP(d[1], d[10]);
  SWAP(d[4], d[6]);
  SWAP(d[9], d[15]);
  SWAP(d[11], d[16]);
  SWAP(d[12], d[17]);
  SWAP(d[13], d[14]);

  /* Stage 5 */
  SWAP(d[0], d[3]);
  SWAP(d[2], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[11]);
  SWAP(d[12], d[16]);

  /* Stage 6 */
  SWAP(d[1], d[8]);
  SWAP(d[2], d[9]);
  SWAP(d[3], d[4]);
  SWAP(d[6], d[15]);
  SWAP(d[7], d[13]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[18]);

  /* Stage 7 */
  SWAP(d[1], d[3]);
  SWAP(d[2], d[5]);
  SWAP(d[6], d[9]);
  SWAP(d[7], d[12]);
  SWAP(d[8], d[10]);
  SWAP(d[11], d[14]);
  SWAP(d[17], d[18]);

  /* Stage 8 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[8]);
  SWAP(d[6], d[10]);
  SWAP(d[9], d[12]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);

  /* Stage 9 */
  SWAP(d[1], d[2]);
  SWAP(d[5], d[8]);
  SWAP(d[6], d[7]);
  SWAP(d[9], d[11]);
  SWAP(d[10], d[13]);
  SWAP(d[14], d[16]);
  SWAP(d[15], d[17]);

  /* Stage 10 */
  SWAP(d[3], d[6]);
  SWAP(d[4], d[5]);
  SWAP(d[7], d[9]);
  SWAP(d[8], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);

  /* Stage 11 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[13]);
  SWAP(d[12], d[14]);

  /* Stage 12 */
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
}

/* Sorting network for 20 elements - 91 comparators */
static inline void sort20(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[3]);
  SWAP(d[1], d[7]);
  SWAP(d[2], d[5]);
  SWAP(d[4], d[8]);
  SWAP(d[6], d[9]);
  SWAP(d[10], d[13]);
  SWAP(d[11], d[15]);
  SWAP(d[12], d[18]);
  SWAP(d[14], d[17]);
  SWAP(d[16], d[19]);

  /* Stage 2 */
  SWAP(d[0], d[14]);
  SWAP(d[1], d[11]);
  SWAP(d[2], d[16]);
  SWAP(d[3], d[17]);
  SWAP(d[4], d[12]);
  SWAP(d[5], d[19]);
  SWAP(d[6], d[10]);
  SWAP(d[7], d[15]);
  SWAP(d[8], d[18]);
  SWAP(d[9], d[13]);

  /* Stage 3 */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[2]);
  SWAP(d[3], d[8]);
  SWAP(d[5], d[7]);
  SWAP(d[11], d[16]);
  SWAP(d[12], d[14]);
  SWAP(d[15], d[19]);
  SWAP(d[17], d[18]);

  /* Stage 4 */
  SWAP(d[1], d[6]);
  SWAP(d[2], d[12]);
  SWAP(d[3], d[5]);
  SWAP(d[4], d[11]);
  SWAP(d[7], d[17]);
  SWAP(d[8], d[15]);
  SWAP(d[13], d[18]);
  SWAP(d[14], d[16]);

  /* Stage 5 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[6]);
  SWAP(d[7], d[10]);
  SWAP(d[9], d[12]);
  SWAP(d[13], d[17]);
  SWAP(d[18], d[19]);

  /* Stage 6 */
  SWAP(d[1], d[6]);
  SWAP(d[5], d[9]);
  SWAP(d[7], d[11]);
  SWAP(d[8], d[12]);
  SWAP(d[10], d[14]);
  SWAP(d[13], d[18]);

  /* Stage 7 */
  SWAP(d[3], d[5]);
  SWAP(d[4], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[12], d[15]);
  SWAP(d[14], d[16]);

  /* Stage 8 */
  SWAP(d[1], d[3]);
  SWAP(d[2], d[4]);
  SWAP(d[5], d[7]);
  SWAP(d[6], d[10]);
  SWAP(d[9], d[13]);
  SWAP(d[12], d[14]);
  SWAP(d[15], d[17]);
  SWAP(d[16], d[18]);

  /* Stage 9 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[4]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[18]);

  /* Stage 10 */
  SWAP(d[2], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[8]);
  SWAP(d[7], d[9]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[14]);
  SWAP(d[13], d[15]);
  SWAP(d[16], d[17]);

  /* Stage 11 */
  SWAP(d[4], d[5]);
  SWAP(d[6], d[8]);
  SWAP(d[7], d[10]);
  SWAP(d[9], d[12]);
  SWAP(d[11], d[13]);
  SWAP(d[14], d[15]);

  /* Stage 12 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);
}

/* Sorting network for 21 elements - 99 comparators */
static inline void sort21(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[18], d[19]);

  /* Stage 2 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[12], d[14]);
  SWAP(d[13], d[15]);
  SWAP(d[16], d[18]);
  SWAP(d[17], d[19]);

  /* Stage 3 */
  SWAP(d[0], d[8]);
  SWAP(d[1], d[9]);
  SWAP(d[2], d[10]);
  SWAP(d[3], d[11]);
  SWAP(d[4], d[12]);
  SWAP(d[5], d[13]);
  SWAP(d[6], d[14]);
  SWAP(d[7], d[15]);

  /* Stage 4 */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[5]);
  SWAP(d[3], d[7]);
  SWAP(d[6], d[20]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[13]);
  SWAP(d[10], d[14]);
  SWAP(d[15], d[19]);

  /* Stage 5 */
  SWAP(d[2], d[6]);
  SWAP(d[3], d[18]);
  SWAP(d[7], d[20]);

  /* Stage 6 */
  SWAP(d[2], d[16]);
  SWAP(d[3], d[6]);
  SWAP(d[5], d[18]);
  SWAP(d[7], d[17]);
  SWAP(d[11], d[20]);

  /* Stage 7 */
  SWAP(d[0], d[2]);
  SWAP(d[3], d[8]);
  SWAP(d[6], d[12]);
  SWAP(d[7], d[10]);
  SWAP(d[9], d[16]);
  SWAP(d[11], d[15]);
  SWAP(d[13], d[17]);
  SWAP(d[14], d[18]);
  SWAP(d[19], d[20]);

  /* Stage 8 */
  SWAP(d[1], d[7]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[13], d[16]);
  SWAP(d[15], d[18]);
  SWAP(d[17], d[19]);

  /* Stage 9 */
  SWAP(d[1], d[4]);
  SWAP(d[5], d[10]);
  SWAP(d[6], d[13]);
  SWAP(d[7], d[8]);
  SWAP(d[11], d[14]);
  SWAP(d[12], d[16]);
  SWAP(d[15], d[17]);
  SWAP(d[18], d[19]);

  /* Stage 10 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[13]);
  SWAP(d[14], d[16]);
  SWAP(d[17], d[18]);

  /* Stage 11 */
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);

  /* Stage 12 */
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[15], d[16]);

  /* Stage 13 */
  SWAP(d[4], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[12]);
  SWAP(d[13], d[15]);

  /* Stage 14 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[12], d[14]);

  /* Stage 15 */
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
}

/* Sorting network for 22 elements - 106 comparators */
static inline void sort22(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[18], d[19]);
  SWAP(d[20], d[21]);

  /* Stage 2 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[13]);
  SWAP(d[14], d[16]);
  SWAP(d[15], d[17]);
  SWAP(d[18], d[20]);
  SWAP(d[19], d[21]);

  /* Stage 3 */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[5]);
  SWAP(d[2], d[6]);
  SWAP(d[3], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[12]);
  SWAP(d[11], d[13]);
  SWAP(d[14], d[18]);
  SWAP(d[15], d[19]);
  SWAP(d[16], d[20]);
  SWAP(d[17], d[21]);

  /* Stage 4 */
  SWAP(d[0], d[14]);
  SWAP(d[1], d[15]);
  SWAP(d[2], d[18]);
  SWAP(d[3], d[19]);
  SWAP(d[4], d[16]);
  SWAP(d[5], d[17]);
  SWAP(d[6], d[20]);
  SWAP(d[7], d[21]);
  SWAP(d[9], d[11]);
  SWAP(d[10], d[12]);

  /* Stage 5 */
  SWAP(d[2], d[8]);
  SWAP(d[3], d[11]);
  SWAP(d[6], d[9]);
  SWAP(d[10], d[18]);
  SWAP(d[12], d[15]);
  SWAP(d[13], d[19]);

  /* Stage 6 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[10]);
  SWAP(d[3], d[16]);
  SWAP(d[5], d[18]);
  SWAP(d[6], d[14]);
  SWAP(d[7], d[15]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[13]);
  SWAP(d[11], d[20]);
  SWAP(d[19], d[21]);

  /* Stage 7 */
  SWAP(d[2], d[6]);
  SWAP(d[3], d[10]);
  SWAP(d[4], d[8]);
  SWAP(d[5], d[12]);
  SWAP(d[9], d[16]);
  SWAP(d[11], d[18]);
  SWAP(d[13], d[17]);
  SWAP(d[15], d[19]);

  /* Stage 8 */
  SWAP(d[1], d[4]);
  SWAP(d[7], d[13]);
  SWAP(d[8], d[14]);
  SWAP(d[9], d[12]);
  SWAP(d[17], d[20]);

  /* Stage 9 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[8]);
  SWAP(d[4], d[6]);
  SWAP(d[7], d[11]);
  SWAP(d[10], d[14]);
  SWAP(d[13], d[18]);
  SWAP(d[15], d[17]);
  SWAP(d[19], d[20]);

  /* Stage 10 */
  SWAP(d[2], d[4]);
  SWAP(d[5], d[10]);
  SWAP(d[7], d[9]);
  SWAP(d[11], d[16]);
  SWAP(d[12], d[14]);
  SWAP(d[17], d[19]);

  /* Stage 11 */
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[11]);
  SWAP(d[10], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);

  /* Stage 12 */
  SWAP(d[3], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[12]);
  SWAP(d[11], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[18]);

  /* Stage 13 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[18]);
}

/* Sorting network for 23 elements - 114 comparators */
static inline void sort23(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[18], d[19]);
  SWAP(d[20], d[21]);

  /* Stage 2 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[12], d[14]);
  SWAP(d[13], d[15]);
  SWAP(d[16], d[18]);
  SWAP(d[17], d[19]);
  SWAP(d[21], d[22]);

  /* Stage 3 */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[5]);
  SWAP(d[2], d[6]);
  SWAP(d[3], d[7]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[13]);
  SWAP(d[10], d[14]);
  SWAP(d[11], d[15]);
  SWAP(d[17], d[21]);
  SWAP(d[18], d[20]);
  SWAP(d[19], d[22]);

  /* Stage 4 */
  SWAP(d[0], d[8]);
  SWAP(d[1], d[9]);
  SWAP(d[2], d[10]);
  SWAP(d[3], d[11]);
  SWAP(d[4], d[12]);
  SWAP(d[5], d[13]);
  SWAP(d[6], d[14]);
  SWAP(d[7], d[15]);

  /* Stage 5 */
  SWAP(d[1], d[2]);
  SWAP(d[5], d[18]);
  SWAP(d[7], d[19]);
  SWAP(d[9], d[16]);
  SWAP(d[10], d[21]);
  SWAP(d[12], d[20]);
  SWAP(d[15], d[22]);

  /* Stage 6 */
  SWAP(d[5], d[9]);
  SWAP(d[6], d[7]);
  SWAP(d[10], d[18]);
  SWAP(d[11], d[21]);
  SWAP(d[12], d[17]);
  SWAP(d[13], d[20]);
  SWAP(d[14], d[15]);

  /* Stage 7 */
  SWAP(d[3], d[17]);
  SWAP(d[6], d[16]);
  SWAP(d[7], d[14]);
  SWAP(d[8], d[12]);
  SWAP(d[15], d[19]);
  SWAP(d[20], d[21]);

  /* Stage 8 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[8]);
  SWAP(d[6], d[10]);
  SWAP(d[9], d[12]);
  SWAP(d[13], d[16]);
  SWAP(d[14], d[15]);
  SWAP(d[17], d[18]);
  SWAP(d[19], d[21]);

  /* Stage 9 */
  SWAP(d[0], d[5]);
  SWAP(d[1], d[8]);
  SWAP(d[2], d[12]);
  SWAP(d[3], d[9]);
  SWAP(d[4], d[10]);
  SWAP(d[7], d[13]);
  SWAP(d[11], d[17]);
  SWAP(d[14], d[16]);
  SWAP(d[18], d[20]);

  /* Stage 10 */
  SWAP(d[2], d[6]);
  SWAP(d[3], d[5]);
  SWAP(d[4], d[8]);
  SWAP(d[7], d[11]);
  SWAP(d[10], d[12]);
  SWAP(d[13], d[18]);
  SWAP(d[14], d[17]);
  SWAP(d[15], d[20]);

  /* Stage 11 */
  SWAP(d[1], d[3]);
  SWAP(d[2], d[5]);
  SWAP(d[6], d[9]);
  SWAP(d[7], d[10]);
  SWAP(d[11], d[13]);
  SWAP(d[12], d[14]);
  SWAP(d[15], d[18]);
  SWAP(d[16], d[17]);
  SWAP(d[19], d[20]);

  /* Stage 12 */
  SWAP(d[2], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[8], d[9]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[19]);

  /* Stage 13 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[17], d[18]);

  /* Stage 14 */
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[16], d[17]);
}

/* Sorting network for 24 elements - 120 comparators */
static inline void sort24(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[20]);
  SWAP(d[1], d[12]);
  SWAP(d[2], d[16]);
  SWAP(d[3], d[23]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[10]);
  SWAP(d[7], d[21]);
  SWAP(d[8], d[14]);
  SWAP(d[9], d[15]);
  SWAP(d[11], d[22]);
  SWAP(d[13], d[18]);
  SWAP(d[17], d[19]);

  /* Stage 2 */
  SWAP(d[0], d[3]);
  SWAP(d[1], d[11]);
  SWAP(d[2], d[7]);
  SWAP(d[4], d[17]);
  SWAP(d[5], d[13]);
  SWAP(d[6], d[19]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[18]);
  SWAP(d[12], d[22]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[21]);
  SWAP(d[20], d[23]);

  /* Stage 3 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[4]);
  SWAP(d[3], d[12]);
  SWAP(d[5], d[8]);
  SWAP(d[6], d[9]);
  SWAP(d[7], d[10]);
  SWAP(d[11], d[20]);
  SWAP(d[13], d[16]);
  SWAP(d[14], d[17]);
  SWAP(d[15], d[18]);
  SWAP(d[19], d[21]);
  SWAP(d[22], d[23]);

  /* Stage 4 */
  SWAP(d[2], d[5]);
  SWAP(d[4], d[8]);
  SWAP(d[6], d[11]);
  SWAP(d[7], d[14]);
  SWAP(d[9], d[16]);
  SWAP(d[12], d[17]);
  SWAP(d[15], d[19]);
  SWAP(d[18], d[21]);

  /* Stage 5 */
  SWAP(d[1], d[8]);
  SWAP(d[3], d[14]);
  SWAP(d[4], d[7]);
  SWAP(d[9], d[20]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[13]);
  SWAP(d[15], d[22]);
  SWAP(d[16], d[19]);

  /* Stage 6 */
  SWAP(d[0], d[7]);
  SWAP(d[1], d[5]);
  SWAP(d[3], d[4]);
  SWAP(d[6], d[11]);
  SWAP(d[8], d[15]);
  SWAP(d[9], d[14]);
  SWAP(d[10], d[13]);
  SWAP(d[12], d[17]);
  SWAP(d[16], d[23]);
  SWAP(d[18], d[22]);
  SWAP(d[19], d[20]);

  /* Stage 7 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[6]);
  SWAP(d[4], d[7]);
  SWAP(d[5], d[9]);
  SWAP(d[8], d[10]);
  SWAP(d[13], d[15]);
  SWAP(d[14], d[18]);
  SWAP(d[16], d[19]);
  SWAP(d[17], d[22]);
  SWAP(d[21], d[23]);

  /* Stage 8 */
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[8]);
  SWAP(d[7], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[16]);
  SWAP(d[15], d[17]);
  SWAP(d[18], d[19]);
  SWAP(d[20], d[21]);

  /* Stage 9 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[6]);
  SWAP(d[4], d[10]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[11]);
  SWAP(d[12], d[14]);
  SWAP(d[13], d[19]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[20]);
  SWAP(d[21], d[22]);

  /* Stage 10 */
  SWAP(d[2], d[3]);
  SWAP(d[5], d[10]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[13], d[18]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[20], d[21]);

  /* Stage 11 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[7]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[13]);
  SWAP(d[16], d[18]);
  SWAP(d[19], d[20]);

  /* Stage 12 */
  SWAP(d[4], d[6]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[12]);
  SWAP(d[11], d[14]);
  SWAP(d[13], d[15]);
  SWAP(d[17], d[19]);

  /* Stage 13 */
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[18]);
}

/* Sorting network for 25 elements - 130 comparators */
static inline void sort25b(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[18], d[19]);
  SWAP(d[20], d[21]);
  SWAP(d[22], d[23]);

  /* Stage 2 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[12], d[14]);
  SWAP(d[13], d[15]);
  SWAP(d[16], d[18]);
  SWAP(d[17], d[19]);
  SWAP(d[21], d[22]);
  SWAP(d[23], d[24]);

  /* Stage 3 */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[5]);
  SWAP(d[2], d[6]);
  SWAP(d[3], d[7]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[13]);
  SWAP(d[10], d[14]);
  SWAP(d[11], d[15]);
  SWAP(d[18], d[21]);
  SWAP(d[20], d[23]);
  SWAP(d[22], d[24]);

  /* Stage 4 */
  SWAP(d[0], d[8]);
  SWAP(d[1], d[9]);
  SWAP(d[2], d[10]);
  SWAP(d[3], d[11]);
  SWAP(d[4], d[12]);
  SWAP(d[5], d[13]);
  SWAP(d[6], d[14]);
  SWAP(d[7], d[15]);
  SWAP(d[16], d[20]);
  SWAP(d[17], d[22]);
  SWAP(d[19], d[24]);
  SWAP(d[21], d[23]);

  /* Stage 5 */
  SWAP(d[1], d[18]);
  SWAP(d[3], d[21]);
  SWAP(d[5], d[23]);
  SWAP(d[6], d[19]);
  SWAP(d[11], d[14]);
  SWAP(d[15], d[24]);

  /* Stage 6 */
  SWAP(d[1], d[16]);
  SWAP(d[3], d[17]);
  SWAP(d[6], d[9]);
  SWAP(d[7], d[11]);
  SWAP(d[13], d[19]);
  SWAP(d[14], d[23]);

  /* Stage 7 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[16]);
  SWAP(d[3], d[8]);
  SWAP(d[7], d[20]);
  SWAP(d[10], d[13]);
  SWAP(d[11], d[22]);
  SWAP(d[15], d[23]);

  /* Stage 8 */
  SWAP(d[1], d[2]);
  SWAP(d[5], d[10]);
  SWAP(d[7], d[18]);
  SWAP(d[11], d[21]);
  SWAP(d[15], d[20]);
  SWAP(d[19], d[22]);

  /* Stage 9 */
  SWAP(d[4], d[7]);
  SWAP(d[5], d[6]);
  SWAP(d[9], d[18]);
  SWAP(d[10], d[17]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[21]);
  SWAP(d[14], d[15]);
  SWAP(d[19], d[20]);
  SWAP(d[22], d[23]);

  /* Stage 10 */
  SWAP(d[3], d[4]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[16]);
  SWAP(d[12], d[17]);
  SWAP(d[13], d[18]);
  SWAP(d[19], d[21]);
  SWAP(d[20], d[22]);

  /* Stage 11 */
  SWAP(d[1], d[3]);
  SWAP(d[2], d[4]);
  SWAP(d[5], d[11]);
  SWAP(d[6], d[16]);
  SWAP(d[7], d[9]);
  SWAP(d[8], d[10]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[19]);
  SWAP(d[15], d[18]);

  /* Stage 12 */
  SWAP(d[2], d[3]);
  SWAP(d[5], d[7]);
  SWAP(d[6], d[9]);
  SWAP(d[8], d[11]);
  SWAP(d[10], d[16]);
  SWAP(d[12], d[14]);
  SWAP(d[15], d[17]);

  /* Stage 13 */
  SWAP(d[3], d[5]);
  SWAP(d[4], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[11]);
  SWAP(d[10], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[18]);

  /* Stage 14 */
  SWAP(d[4], d[7]);
  SWAP(d[6], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[15]);
  SWAP(d[14], d[16]);
  SWAP(d[17], d[19]);
  SWAP(d[18], d[21]);

  /* Stage 15 */
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[18], d[19]);
  SWAP(d[20], d[21]);
}

/* Sorting network for 25 elements (5x5 window) - Hybrid approach */
static inline void sort25(double *d)
{
  /* Hybrid approach using sort9 for pre-sorting, then insertion sort.
   * This is faster than a pure sorting network for 25 elements (which would need ~120+ comparators).
   * The sort9 networks create a partially sorted structure that makes insertion sort very efficient.
   */

  /* Sort 4 groups of 9 elements using the sort9 network */
  sort9(&d[0]); /* First 3x3 block */
  sort9(&d[9]); /* Second 3x3 block (shifted by 9) */

  /* Now sort the remaining 7 elements mixed with the pre-sorted blocks */
  sort9(&d[16]); /* Elements 16-24 */

  /* Complete the sort using insertion sort on the mostly-sorted array */
  for (int i = 1; i < 25; i++)
  {
    double key = d[i];
    int j = i - 1;
    while (j >= 0 && d[j] > key)
    {
      d[j + 1] = d[j];
      j--;
    }
    d[j + 1] = key;
  }
}

/* Sorting network for 26 elements - 115 comparators */
static inline void sort26(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[18], d[19]);
  SWAP(d[20], d[21]);
  SWAP(d[22], d[23]);
  SWAP(d[24], d[25]);

  /* Stage 2 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[14], d[16]);
  SWAP(d[15], d[17]);
  SWAP(d[18], d[20]);
  SWAP(d[19], d[21]);
  SWAP(d[22], d[24]);
  SWAP(d[23], d[25]);

  /* Stage 3 */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[6]);
  SWAP(d[2], d[5]);
  SWAP(d[3], d[7]);
  SWAP(d[8], d[14]);
  SWAP(d[9], d[16]);
  SWAP(d[10], d[15]);
  SWAP(d[11], d[17]);
  SWAP(d[18], d[22]);
  SWAP(d[19], d[24]);
  SWAP(d[20], d[23]);
  SWAP(d[21], d[25]);

  /* Stage 4 */
  SWAP(d[0], d[18]);
  SWAP(d[1], d[19]);
  SWAP(d[2], d[20]);
  SWAP(d[3], d[21]);
  SWAP(d[4], d[22]);
  SWAP(d[5], d[23]);
  SWAP(d[6], d[24]);
  SWAP(d[7], d[25]);
  SWAP(d[9], d[12]);
  SWAP(d[13], d[16]);

  /* Stage 5 */
  SWAP(d[3], d[11]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[13]);
  SWAP(d[12], d[15]);
  SWAP(d[14], d[22]);
  SWAP(d[16], d[17]);

  /* Stage 6 */
  SWAP(d[0], d[8]);
  SWAP(d[1], d[9]);
  SWAP(d[2], d[14]);
  SWAP(d[6], d[12]);
  SWAP(d[7], d[15]);
  SWAP(d[10], d[18]);
  SWAP(d[11], d[23]);
  SWAP(d[13], d[19]);
  SWAP(d[16], d[24]);
  SWAP(d[17], d[25]);

  /* Stage 7 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[18]);
  SWAP(d[4], d[8]);
  SWAP(d[7], d[22]);
  SWAP(d[17], d[21]);
  SWAP(d[23], d[24]);

  /* Stage 8 */
  SWAP(d[3], d[14]);
  SWAP(d[4], d[10]);
  SWAP(d[5], d[18]);
  SWAP(d[7], d[20]);
  SWAP(d[8], d[13]);
  SWAP(d[11], d[22]);
  SWAP(d[12], d[17]);
  SWAP(d[15], d[21]);

  /* Stage 9 */
  SWAP(d[1], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[9]);
  SWAP(d[8], d[10]);
  SWAP(d[15], d[17]);
  SWAP(d[16], d[18]);
  SWAP(d[19], d[20]);
  SWAP(d[21], d[24]);

  /* Stage 10 */
  SWAP(d[2], d[5]);
  SWAP(d[3], d[10]);
  SWAP(d[6], d[14]);
  SWAP(d[9], d[13]);
  SWAP(d[11], d[19]);
  SWAP(d[12], d[16]);
  SWAP(d[15], d[22]);
  SWAP(d[20], d[23]);

  /* Stage 11 */
  SWAP(d[2], d[8]);
  SWAP(d[5], d[7]);
  SWAP(d[6], d[9]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[16], d[19]);
  SWAP(d[17], d[23]);
  SWAP(d[18], d[20]);

  /* Stage 12 */
  SWAP(d[2], d[4]);
  SWAP(d[3], d[5]);
  SWAP(d[6], d[11]);
  SWAP(d[7], d[10]);
  SWAP(d[9], d[16]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[19]);
  SWAP(d[15], d[18]);
  SWAP(d[20], d[22]);
  SWAP(d[21], d[23]);

  /* Stage 13 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[8]);
  SWAP(d[6], d[7]);
  SWAP(d[9], d[11]);
  SWAP(d[10], d[12]);
  SWAP(d[13], d[15]);
  SWAP(d[14], d[16]);
  SWAP(d[17], d[20]);
  SWAP(d[18], d[19]);
  SWAP(d[21], d[22]);

  /* Stage 14 */
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[18]);
  SWAP(d[19], d[20]);

  /* Stage 15 */
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[18], d[19]);
  SWAP(d[20], d[21]);
}

/* Sorting network for 27 elements (3x3x3 window) - Hybrid approach */
static inline void sort27(double *d)
{
  /* Hybrid approach for 27 elements.
   * A pure sorting network for 27 elements is complex (~170-200 comparators).
   * This hybrid uses proven sorting networks for initial structure,
   * then completes with insertion sort.
   * Performance: The pre-sorting makes insertion sort very efficient (mostly sorted input).
   * Correctness: Guaranteed by insertion sort.
   */

  /* Stage 1: Sort 9 groups of 3 elements each using sort3 network (27 comparators) */
  sort3(&d[0]);
  sort3(&d[3]);
  sort3(&d[6]);
  sort3(&d[9]);
  sort3(&d[12]);
  sort3(&d[15]);
  sort3(&d[18]);
  sort3(&d[21]);
  sort3(&d[24]);

  /* Stage 2: Sort 3 groups of 9 elements each using sort9 network */
  sort9(&d[0]);
  sort9(&d[9]);
  sort9(&d[18]);

  /* Stage 3: Complete the sort using insertion sort on the mostly-sorted array */
  for (int i = 1; i < 27; i++)
  {
    double key = d[i];
    int j = i - 1;
    while (j >= 0 && d[j] > key)
    {
      d[j + 1] = d[j];
      j--;
    }
    d[j + 1] = key;
  }
}

/* Complete sorting network for 27 elements - 114 comparators */
static inline void sort27b(double *d)
{
  /* Stage 1 */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[14]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[18]);
  SWAP(d[19], d[20]);
  SWAP(d[21], d[22]);
  SWAP(d[23], d[24]);
  SWAP(d[25], d[26]);

  /* Stage 2 */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[15], d[17]);
  SWAP(d[16], d[18]);
  SWAP(d[19], d[21]);
  SWAP(d[20], d[22]);
  SWAP(d[23], d[25]);
  SWAP(d[24], d[26]);

  /* Stage 3 */
  SWAP(d[0], d[23]);
  SWAP(d[1], d[24]);
  SWAP(d[2], d[25]);
  SWAP(d[3], d[26]);
  SWAP(d[4], d[8]);
  SWAP(d[5], d[9]);
  SWAP(d[6], d[10]);
  SWAP(d[7], d[11]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[19]);
  SWAP(d[16], d[20]);
  SWAP(d[17], d[21]);
  SWAP(d[18], d[22]);

  /* Stage 4 */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[6]);
  SWAP(d[2], d[19]);
  SWAP(d[3], d[20]);
  SWAP(d[5], d[13]);
  SWAP(d[9], d[21]);
  SWAP(d[11], d[14]);
  SWAP(d[12], d[16]);
  SWAP(d[17], d[23]);
  SWAP(d[18], d[24]);
  SWAP(d[22], d[26]);

  /* Stage 5 */
  SWAP(d[5], d[17]);
  SWAP(d[6], d[16]);
  SWAP(d[7], d[22]);
  SWAP(d[9], d[25]);
  SWAP(d[10], d[24]);
  SWAP(d[12], d[15]);
  SWAP(d[13], d[20]);
  SWAP(d[14], d[26]);

  /* Stage 6 */
  SWAP(d[1], d[12]);
  SWAP(d[4], d[15]);
  SWAP(d[7], d[23]);
  SWAP(d[10], d[19]);
  SWAP(d[11], d[16]);
  SWAP(d[13], d[18]);
  SWAP(d[20], d[24]);
  SWAP(d[22], d[25]);

  /* Stage 7 */
  SWAP(d[0], d[1]);
  SWAP(d[6], d[12]);
  SWAP(d[8], d[11]);
  SWAP(d[9], d[15]);
  SWAP(d[10], d[17]);
  SWAP(d[14], d[24]);
  SWAP(d[16], d[21]);
  SWAP(d[18], d[19]);

  /* Stage 8 */
  SWAP(d[1], d[4]);
  SWAP(d[2], d[8]);
  SWAP(d[3], d[11]);
  SWAP(d[12], d[15]);
  SWAP(d[14], d[20]);
  SWAP(d[16], d[22]);
  SWAP(d[21], d[25]);

  /* Stage 9 */
  SWAP(d[2], d[5]);
  SWAP(d[3], d[17]);
  SWAP(d[8], d[13]);
  SWAP(d[11], d[23]);
  SWAP(d[21], d[22]);
  SWAP(d[24], d[25]);

  /* Stage 10 */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[10]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[13]);
  SWAP(d[11], d[15]);
  SWAP(d[14], d[21]);
  SWAP(d[18], d[23]);
  SWAP(d[20], d[22]);

  /* Stage 11 */
  SWAP(d[4], d[5]);
  SWAP(d[6], d[9]);
  SWAP(d[7], d[8]);
  SWAP(d[13], d[17]);
  SWAP(d[14], d[16]);
  SWAP(d[19], d[23]);
  SWAP(d[22], d[24]);

  /* Stage 12 */
  SWAP(d[2], d[4]);
  SWAP(d[3], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[13]);
  SWAP(d[14], d[18]);
  SWAP(d[15], d[17]);
  SWAP(d[16], d[19]);
  SWAP(d[21], d[23]);

  /* Stage 13 */
  SWAP(d[3], d[5]);
  SWAP(d[6], d[8]);
  SWAP(d[7], d[9]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[14]);
  SWAP(d[13], d[16]);
  SWAP(d[15], d[18]);
  SWAP(d[17], d[19]);
  SWAP(d[20], d[21]);
  SWAP(d[22], d[23]);

  /* Stage 14 */
  SWAP(d[5], d[6]);
  SWAP(d[8], d[11]);
  SWAP(d[9], d[10]);
  SWAP(d[12], d[14]);
  SWAP(d[13], d[15]);
  SWAP(d[17], d[18]);
  SWAP(d[19], d[21]);

  /* Stage 15 */
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[18], d[20]);
  SWAP(d[21], d[22]);

  /* Stage 16 */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[18]);
  SWAP(d[19], d[20]);
}

/* ============================================================================
   Optimal Sorting Networks for N=28-32
   ============================================================================ */

/* sort28: 28 elements, 14 stages, 155 comparators */
void sort28(double *d)
{
  /* Stage 1: 14 comparators */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[18], d[19]);
  SWAP(d[20], d[21]);
  SWAP(d[22], d[23]);
  SWAP(d[24], d[25]);
  SWAP(d[26], d[27]);

  /* Stage 2: 14 comparators */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[12], d[14]);
  SWAP(d[13], d[15]);
  SWAP(d[16], d[18]);
  SWAP(d[17], d[19]);
  SWAP(d[20], d[22]);
  SWAP(d[21], d[23]);
  SWAP(d[24], d[26]);
  SWAP(d[25], d[27]);

  /* Stage 3: 12 comparators */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[5]);
  SWAP(d[2], d[6]);
  SWAP(d[3], d[7]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[13]);
  SWAP(d[14], d[18]);
  SWAP(d[15], d[19]);
  SWAP(d[20], d[24]);
  SWAP(d[21], d[25]);
  SWAP(d[22], d[26]);
  SWAP(d[23], d[27]);

  /* Stage 4: 12 comparators */
  SWAP(d[0], d[20]);
  SWAP(d[1], d[21]);
  SWAP(d[2], d[22]);
  SWAP(d[3], d[23]);
  SWAP(d[4], d[24]);
  SWAP(d[5], d[25]);
  SWAP(d[6], d[26]);
  SWAP(d[7], d[27]);
  SWAP(d[9], d[17]);
  SWAP(d[10], d[18]);
  SWAP(d[11], d[15]);
  SWAP(d[12], d[16]);

  /* Stage 5: 12 comparators */
  SWAP(d[1], d[2]);
  SWAP(d[4], d[20]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[23]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[16]);
  SWAP(d[10], d[14]);
  SWAP(d[11], d[18]);
  SWAP(d[13], d[17]);
  SWAP(d[15], d[19]);
  SWAP(d[21], d[22]);
  SWAP(d[25], d[26]);

  /* Stage 6: 14 comparators */
  SWAP(d[0], d[8]);
  SWAP(d[1], d[9]);
  SWAP(d[2], d[12]);
  SWAP(d[3], d[5]);
  SWAP(d[4], d[10]);
  SWAP(d[6], d[16]);
  SWAP(d[7], d[13]);
  SWAP(d[11], d[21]);
  SWAP(d[14], d[20]);
  SWAP(d[15], d[25]);
  SWAP(d[17], d[23]);
  SWAP(d[18], d[26]);
  SWAP(d[19], d[27]);
  SWAP(d[22], d[24]);

  /* Stage 7: 10 comparators */
  SWAP(d[2], d[4]);
  SWAP(d[3], d[7]);
  SWAP(d[5], d[17]);
  SWAP(d[8], d[14]);
  SWAP(d[9], d[11]);
  SWAP(d[10], d[22]);
  SWAP(d[13], d[19]);
  SWAP(d[16], d[18]);
  SWAP(d[20], d[24]);
  SWAP(d[23], d[25]);

  /* Stage 8: 10 comparators */
  SWAP(d[1], d[8]);
  SWAP(d[3], d[9]);
  SWAP(d[5], d[11]);
  SWAP(d[6], d[10]);
  SWAP(d[7], d[15]);
  SWAP(d[12], d[20]);
  SWAP(d[16], d[22]);
  SWAP(d[17], d[21]);
  SWAP(d[18], d[24]);
  SWAP(d[19], d[26]);

  /* Stage 9: 10 comparators */
  SWAP(d[1], d[2]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[9]);
  SWAP(d[10], d[16]);
  SWAP(d[11], d[17]);
  SWAP(d[12], d[14]);
  SWAP(d[13], d[15]);
  SWAP(d[18], d[22]);
  SWAP(d[21], d[23]);
  SWAP(d[25], d[26]);

  /* Stage 10: 8 comparators */
  SWAP(d[4], d[8]);
  SWAP(d[6], d[12]);
  SWAP(d[7], d[11]);
  SWAP(d[10], d[14]);
  SWAP(d[13], d[17]);
  SWAP(d[15], d[21]);
  SWAP(d[16], d[20]);
  SWAP(d[19], d[23]);

  /* Stage 11: 10 comparators */
  SWAP(d[2], d[4]);
  SWAP(d[6], d[8]);
  SWAP(d[7], d[16]);
  SWAP(d[9], d[14]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[20]);
  SWAP(d[13], d[18]);
  SWAP(d[15], d[17]);
  SWAP(d[19], d[21]);
  SWAP(d[23], d[25]);

  /* Stage 12: 8 comparators */
  SWAP(d[3], d[10]);
  SWAP(d[5], d[12]);
  SWAP(d[7], d[9]);
  SWAP(d[11], d[13]);
  SWAP(d[14], d[16]);
  SWAP(d[15], d[22]);
  SWAP(d[17], d[24]);
  SWAP(d[18], d[20]);

  /* Stage 13: 10 comparators */
  SWAP(d[3], d[6]);
  SWAP(d[5], d[8]);
  SWAP(d[7], d[10]);
  SWAP(d[9], d[12]);
  SWAP(d[11], d[14]);
  SWAP(d[13], d[16]);
  SWAP(d[15], d[18]);
  SWAP(d[17], d[20]);
  SWAP(d[19], d[22]);
  SWAP(d[21], d[24]);

  /* Stage 14: 11 comparators */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[18]);
  SWAP(d[19], d[20]);
  SWAP(d[21], d[22]);
  SWAP(d[23], d[24]);
}

/* sort29: 29 elements, 15 stages, 164 comparators */
void sort29(double *d)
{
  /* Stage 1: 14 comparators */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[28]);
  SWAP(d[17], d[26]);
  SWAP(d[18], d[25]);
  SWAP(d[19], d[23]);
  SWAP(d[21], d[27]);
  SWAP(d[22], d[24]);

  /* Stage 2: 13 comparators */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[12], d[14]);
  SWAP(d[13], d[15]);
  SWAP(d[17], d[22]);
  SWAP(d[18], d[19]);
  SWAP(d[20], d[27]);
  SWAP(d[23], d[25]);
  SWAP(d[24], d[26]);

  /* Stage 3: 14 comparators */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[5]);
  SWAP(d[2], d[6]);
  SWAP(d[3], d[7]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[13]);
  SWAP(d[10], d[14]);
  SWAP(d[11], d[15]);
  SWAP(d[16], d[20]);
  SWAP(d[17], d[18]);
  SWAP(d[19], d[22]);
  SWAP(d[23], d[24]);
  SWAP(d[25], d[26]);
  SWAP(d[27], d[28]);

  /* Stage 4: 13 comparators */
  SWAP(d[0], d[8]);
  SWAP(d[1], d[9]);
  SWAP(d[2], d[10]);
  SWAP(d[3], d[11]);
  SWAP(d[4], d[12]);
  SWAP(d[5], d[13]);
  SWAP(d[6], d[14]);
  SWAP(d[7], d[15]);
  SWAP(d[16], d[18]);
  SWAP(d[20], d[22]);
  SWAP(d[21], d[25]);
  SWAP(d[24], d[27]);
  SWAP(d[26], d[28]);

  /* Stage 5: 13 comparators */
  SWAP(d[1], d[8]);
  SWAP(d[2], d[24]);
  SWAP(d[4], d[19]);
  SWAP(d[5], d[20]);
  SWAP(d[6], d[21]);
  SWAP(d[7], d[27]);
  SWAP(d[9], d[18]);
  SWAP(d[10], d[23]);
  SWAP(d[11], d[26]);
  SWAP(d[13], d[22]);
  SWAP(d[14], d[25]);
  SWAP(d[15], d[28]);
  SWAP(d[16], d[17]);

  /* Stage 6: 10 comparators */
  SWAP(d[0], d[6]);
  SWAP(d[2], d[4]);
  SWAP(d[3], d[24]);
  SWAP(d[5], d[10]);
  SWAP(d[12], d[19]);
  SWAP(d[13], d[18]);
  SWAP(d[14], d[21]);
  SWAP(d[15], d[25]);
  SWAP(d[20], d[23]);
  SWAP(d[26], d[27]);

  /* Stage 7: 11 comparators */
  SWAP(d[0], d[16]);
  SWAP(d[1], d[6]);
  SWAP(d[3], d[12]);
  SWAP(d[4], d[8]);
  SWAP(d[5], d[17]);
  SWAP(d[7], d[24]);
  SWAP(d[14], d[20]);
  SWAP(d[15], d[26]);
  SWAP(d[18], d[21]);
  SWAP(d[19], d[23]);
  SWAP(d[25], d[27]);

  /* Stage 8: 11 comparators */
  SWAP(d[1], d[5]);
  SWAP(d[2], d[16]);
  SWAP(d[3], d[10]);
  SWAP(d[6], d[9]);
  SWAP(d[7], d[18]);
  SWAP(d[8], d[17]);
  SWAP(d[11], d[19]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[22]);
  SWAP(d[21], d[23]);
  SWAP(d[25], d[26]);

  /* Stage 9: 11 comparators */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[5]);
  SWAP(d[4], d[8]);
  SWAP(d[6], d[16]);
  SWAP(d[7], d[11]);
  SWAP(d[9], d[17]);
  SWAP(d[10], d[12]);
  SWAP(d[14], d[20]);
  SWAP(d[15], d[18]);
  SWAP(d[19], d[24]);
  SWAP(d[22], d[27]);

  /* Stage 10: 8 comparators */
  SWAP(d[4], d[6]);
  SWAP(d[9], d[16]);
  SWAP(d[10], d[13]);
  SWAP(d[11], d[19]);
  SWAP(d[12], d[14]);
  SWAP(d[20], d[21]);
  SWAP(d[22], d[26]);
  SWAP(d[23], d[24]);

  /* Stage 11: 8 comparators */
  SWAP(d[2], d[4]);
  SWAP(d[3], d[6]);
  SWAP(d[7], d[16]);
  SWAP(d[8], d[9]);
  SWAP(d[11], d[17]);
  SWAP(d[15], d[19]);
  SWAP(d[18], d[23]);
  SWAP(d[24], d[25]);

  /* Stage 12: 9 comparators */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[9]);
  SWAP(d[7], d[10]);
  SWAP(d[11], d[13]);
  SWAP(d[12], d[16]);
  SWAP(d[14], d[17]);
  SWAP(d[15], d[20]);
  SWAP(d[19], d[21]);
  SWAP(d[22], d[24]);

  /* Stage 13: 10 comparators */
  SWAP(d[5], d[8]);
  SWAP(d[6], d[7]);
  SWAP(d[9], d[12]);
  SWAP(d[10], d[11]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[20]);
  SWAP(d[18], d[19]);
  SWAP(d[21], d[23]);
  SWAP(d[24], d[25]);

  /* Stage 14: 9 comparators */
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[15]);
  SWAP(d[14], d[16]);
  SWAP(d[17], d[18]);
  SWAP(d[19], d[20]);
  SWAP(d[21], d[22]);

  /* Stage 15: 10 comparators */
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[18], d[19]);
  SWAP(d[20], d[21]);
  SWAP(d[22], d[23]);
}

/* sort30: 30 elements, 14 stages, 172 comparators */
void sort30(double *d)
{
  /* Stage 1: 15 comparators */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[18], d[19]);
  SWAP(d[20], d[21]);
  SWAP(d[22], d[23]);
  SWAP(d[24], d[25]);
  SWAP(d[26], d[27]);
  SWAP(d[28], d[29]);

  /* Stage 2: 14 comparators */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[13], d[15]);
  SWAP(d[14], d[16]);
  SWAP(d[18], d[20]);
  SWAP(d[19], d[21]);
  SWAP(d[22], d[24]);
  SWAP(d[23], d[25]);
  SWAP(d[26], d[28]);
  SWAP(d[27], d[29]);

  /* Stage 3: 14 comparators */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[5]);
  SWAP(d[2], d[6]);
  SWAP(d[3], d[7]);
  SWAP(d[8], d[14]);
  SWAP(d[9], d[17]);
  SWAP(d[10], d[16]);
  SWAP(d[12], d[20]);
  SWAP(d[13], d[19]);
  SWAP(d[15], d[21]);
  SWAP(d[22], d[26]);
  SWAP(d[23], d[27]);
  SWAP(d[24], d[28]);
  SWAP(d[25], d[29]);

  /* Stage 4: 14 comparators */
  SWAP(d[0], d[8]);
  SWAP(d[1], d[9]);
  SWAP(d[2], d[14]);
  SWAP(d[3], d[17]);
  SWAP(d[4], d[10]);
  SWAP(d[5], d[11]);
  SWAP(d[6], d[16]);
  SWAP(d[12], d[26]);
  SWAP(d[13], d[23]);
  SWAP(d[15], d[27]);
  SWAP(d[18], d[24]);
  SWAP(d[19], d[25]);
  SWAP(d[20], d[28]);
  SWAP(d[21], d[29]);

  /* Stage 5: 14 comparators */
  SWAP(d[1], d[13]);
  SWAP(d[2], d[12]);
  SWAP(d[3], d[15]);
  SWAP(d[4], d[18]);
  SWAP(d[5], d[19]);
  SWAP(d[6], d[20]);
  SWAP(d[7], d[21]);
  SWAP(d[8], d[22]);
  SWAP(d[9], d[23]);
  SWAP(d[10], d[24]);
  SWAP(d[11], d[25]);
  SWAP(d[14], d[26]);
  SWAP(d[16], d[28]);
  SWAP(d[17], d[27]);

  /* Stage 6: 14 comparators */
  SWAP(d[0], d[4]);
  SWAP(d[2], d[8]);
  SWAP(d[3], d[13]);
  SWAP(d[5], d[9]);
  SWAP(d[6], d[22]);
  SWAP(d[7], d[23]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[15]);
  SWAP(d[14], d[18]);
  SWAP(d[16], d[26]);
  SWAP(d[17], d[19]);
  SWAP(d[20], d[24]);
  SWAP(d[21], d[27]);
  SWAP(d[25], d[29]);

  /* Stage 7: 12 comparators */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[14]);
  SWAP(d[3], d[5]);
  SWAP(d[4], d[8]);
  SWAP(d[9], d[13]);
  SWAP(d[11], d[17]);
  SWAP(d[12], d[18]);
  SWAP(d[15], d[28]);
  SWAP(d[16], d[20]);
  SWAP(d[21], d[25]);
  SWAP(d[24], d[26]);
  SWAP(d[27], d[29]);

  /* Stage 8: 10 comparators */
  SWAP(d[2], d[4]);
  SWAP(d[5], d[9]);
  SWAP(d[6], d[14]);
  SWAP(d[7], d[13]);
  SWAP(d[8], d[10]);
  SWAP(d[15], d[23]);
  SWAP(d[16], d[22]);
  SWAP(d[19], d[21]);
  SWAP(d[20], d[24]);
  SWAP(d[25], d[27]);

  /* Stage 9: 8 comparators */
  SWAP(d[6], d[8]);
  SWAP(d[7], d[11]);
  SWAP(d[10], d[14]);
  SWAP(d[12], d[16]);
  SWAP(d[13], d[17]);
  SWAP(d[15], d[19]);
  SWAP(d[18], d[22]);
  SWAP(d[21], d[23]);

  /* Stage 10: 10 comparators */
  SWAP(d[4], d[6]);
  SWAP(d[7], d[9]);
  SWAP(d[8], d[10]);
  SWAP(d[11], d[13]);
  SWAP(d[12], d[14]);
  SWAP(d[15], d[17]);
  SWAP(d[16], d[18]);
  SWAP(d[19], d[21]);
  SWAP(d[20], d[22]);
  SWAP(d[23], d[25]);

  /* Stage 11: 11 comparators */
  SWAP(d[1], d[8]);
  SWAP(d[3], d[18]);
  SWAP(d[5], d[20]);
  SWAP(d[7], d[22]);
  SWAP(d[9], d[24]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[26]);
  SWAP(d[13], d[15]);
  SWAP(d[14], d[16]);
  SWAP(d[17], d[19]);
  SWAP(d[21], d[28]);

  /* Stage 12: 11 comparators */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[10]);
  SWAP(d[5], d[12]);
  SWAP(d[7], d[14]);
  SWAP(d[9], d[16]);
  SWAP(d[11], d[18]);
  SWAP(d[13], d[20]);
  SWAP(d[15], d[22]);
  SWAP(d[17], d[24]);
  SWAP(d[19], d[26]);
  SWAP(d[27], d[28]);

  /* Stage 13: 13 comparators */
  SWAP(d[2], d[4]);
  SWAP(d[3], d[6]);
  SWAP(d[5], d[8]);
  SWAP(d[7], d[10]);
  SWAP(d[9], d[12]);
  SWAP(d[11], d[14]);
  SWAP(d[13], d[16]);
  SWAP(d[15], d[18]);
  SWAP(d[17], d[20]);
  SWAP(d[19], d[22]);
  SWAP(d[21], d[24]);
  SWAP(d[23], d[26]);
  SWAP(d[25], d[27]);

  /* Stage 14: 12 comparators */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[18]);
  SWAP(d[19], d[20]);
  SWAP(d[21], d[22]);
  SWAP(d[23], d[24]);
  SWAP(d[25], d[26]);
}

/* sort31: 31 elements, 14 stages, 180 comparators */
void sort31(double *d)
{
  /* Stage 1: 15 comparators */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[18], d[19]);
  SWAP(d[20], d[21]);
  SWAP(d[22], d[23]);
  SWAP(d[24], d[25]);
  SWAP(d[26], d[27]);
  SWAP(d[28], d[29]);

  /* Stage 2: 15 comparators */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[12], d[14]);
  SWAP(d[13], d[15]);
  SWAP(d[16], d[18]);
  SWAP(d[17], d[19]);
  SWAP(d[20], d[22]);
  SWAP(d[21], d[23]);
  SWAP(d[24], d[26]);
  SWAP(d[25], d[27]);
  SWAP(d[28], d[30]);

  /* Stage 3: 15 comparators */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[5]);
  SWAP(d[2], d[6]);
  SWAP(d[3], d[7]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[13]);
  SWAP(d[10], d[14]);
  SWAP(d[11], d[15]);
  SWAP(d[16], d[20]);
  SWAP(d[17], d[21]);
  SWAP(d[18], d[22]);
  SWAP(d[19], d[23]);
  SWAP(d[24], d[28]);
  SWAP(d[25], d[29]);
  SWAP(d[26], d[30]);

  /* Stage 4: 15 comparators */
  SWAP(d[0], d[8]);
  SWAP(d[1], d[9]);
  SWAP(d[2], d[10]);
  SWAP(d[3], d[11]);
  SWAP(d[4], d[12]);
  SWAP(d[5], d[13]);
  SWAP(d[6], d[14]);
  SWAP(d[7], d[15]);
  SWAP(d[16], d[24]);
  SWAP(d[17], d[25]);
  SWAP(d[18], d[26]);
  SWAP(d[19], d[27]);
  SWAP(d[20], d[28]);
  SWAP(d[21], d[29]);
  SWAP(d[22], d[30]);

  /* Stage 5: 15 comparators */
  SWAP(d[0], d[16]);
  SWAP(d[1], d[8]);
  SWAP(d[2], d[4]);
  SWAP(d[3], d[12]);
  SWAP(d[5], d[10]);
  SWAP(d[6], d[9]);
  SWAP(d[7], d[14]);
  SWAP(d[11], d[13]);
  SWAP(d[17], d[24]);
  SWAP(d[18], d[20]);
  SWAP(d[19], d[28]);
  SWAP(d[21], d[26]);
  SWAP(d[22], d[25]);
  SWAP(d[23], d[30]);
  SWAP(d[27], d[29]);

  /* Stage 6: 14 comparators */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[5]);
  SWAP(d[4], d[8]);
  SWAP(d[6], d[22]);
  SWAP(d[7], d[11]);
  SWAP(d[9], d[25]);
  SWAP(d[10], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[17], d[18]);
  SWAP(d[19], d[21]);
  SWAP(d[20], d[24]);
  SWAP(d[23], d[27]);
  SWAP(d[26], d[28]);
  SWAP(d[29], d[30]);

  /* Stage 7: 12 comparators */
  SWAP(d[1], d[17]);
  SWAP(d[2], d[18]);
  SWAP(d[3], d[19]);
  SWAP(d[4], d[20]);
  SWAP(d[5], d[10]);
  SWAP(d[7], d[23]);
  SWAP(d[8], d[24]);
  SWAP(d[11], d[27]);
  SWAP(d[12], d[28]);
  SWAP(d[13], d[29]);
  SWAP(d[14], d[30]);
  SWAP(d[21], d[26]);

  /* Stage 8: 12 comparators */
  SWAP(d[3], d[17]);
  SWAP(d[4], d[16]);
  SWAP(d[5], d[21]);
  SWAP(d[6], d[18]);
  SWAP(d[7], d[9]);
  SWAP(d[8], d[20]);
  SWAP(d[10], d[26]);
  SWAP(d[11], d[23]);
  SWAP(d[13], d[25]);
  SWAP(d[14], d[28]);
  SWAP(d[15], d[27]);
  SWAP(d[22], d[24]);

  /* Stage 9: 12 comparators */
  SWAP(d[1], d[4]);
  SWAP(d[3], d[8]);
  SWAP(d[5], d[16]);
  SWAP(d[7], d[17]);
  SWAP(d[9], d[21]);
  SWAP(d[10], d[22]);
  SWAP(d[11], d[19]);
  SWAP(d[12], d[20]);
  SWAP(d[14], d[24]);
  SWAP(d[15], d[26]);
  SWAP(d[23], d[28]);
  SWAP(d[27], d[30]);

  /* Stage 10: 10 comparators */
  SWAP(d[2], d[5]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[18]);
  SWAP(d[11], d[17]);
  SWAP(d[12], d[16]);
  SWAP(d[13], d[22]);
  SWAP(d[14], d[20]);
  SWAP(d[15], d[19]);
  SWAP(d[23], d[24]);
  SWAP(d[26], d[29]);

  /* Stage 11: 10 comparators */
  SWAP(d[2], d[4]);
  SWAP(d[6], d[12]);
  SWAP(d[9], d[16]);
  SWAP(d[10], d[11]);
  SWAP(d[13], d[17]);
  SWAP(d[14], d[18]);
  SWAP(d[15], d[22]);
  SWAP(d[19], d[25]);
  SWAP(d[20], d[21]);
  SWAP(d[27], d[29]);

  /* Stage 12: 10 comparators */
  SWAP(d[5], d[6]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[13]);
  SWAP(d[14], d[16]);
  SWAP(d[15], d[17]);
  SWAP(d[18], d[20]);
  SWAP(d[19], d[23]);
  SWAP(d[21], d[22]);
  SWAP(d[25], d[26]);

  /* Stage 13: 12 comparators */
  SWAP(d[3], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[14]);
  SWAP(d[13], d[16]);
  SWAP(d[15], d[18]);
  SWAP(d[17], d[20]);
  SWAP(d[19], d[21]);
  SWAP(d[22], d[23]);
  SWAP(d[24], d[25]);
  SWAP(d[26], d[28]);

  /* Stage 14: 13 comparators */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[18]);
  SWAP(d[19], d[20]);
  SWAP(d[21], d[22]);
  SWAP(d[23], d[24]);
  SWAP(d[25], d[26]);
  SWAP(d[27], d[28]);
}

/* sort32: 32 elements, 14 stages, 185 comparators */
void sort32(double *d)
{
  /* Stage 1: 16 comparators */
  SWAP(d[0], d[1]);
  SWAP(d[2], d[3]);
  SWAP(d[4], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[11]);
  SWAP(d[12], d[13]);
  SWAP(d[14], d[15]);
  SWAP(d[16], d[17]);
  SWAP(d[18], d[19]);
  SWAP(d[20], d[21]);
  SWAP(d[22], d[23]);
  SWAP(d[24], d[25]);
  SWAP(d[26], d[27]);
  SWAP(d[28], d[29]);
  SWAP(d[30], d[31]);

  /* Stage 2: 16 comparators */
  SWAP(d[0], d[2]);
  SWAP(d[1], d[3]);
  SWAP(d[4], d[6]);
  SWAP(d[5], d[7]);
  SWAP(d[8], d[10]);
  SWAP(d[9], d[11]);
  SWAP(d[12], d[14]);
  SWAP(d[13], d[15]);
  SWAP(d[16], d[18]);
  SWAP(d[17], d[19]);
  SWAP(d[20], d[22]);
  SWAP(d[21], d[23]);
  SWAP(d[24], d[26]);
  SWAP(d[25], d[27]);
  SWAP(d[28], d[30]);
  SWAP(d[29], d[31]);

  /* Stage 3: 16 comparators */
  SWAP(d[0], d[4]);
  SWAP(d[1], d[5]);
  SWAP(d[2], d[6]);
  SWAP(d[3], d[7]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[13]);
  SWAP(d[10], d[14]);
  SWAP(d[11], d[15]);
  SWAP(d[16], d[20]);
  SWAP(d[17], d[21]);
  SWAP(d[18], d[22]);
  SWAP(d[19], d[23]);
  SWAP(d[24], d[28]);
  SWAP(d[25], d[29]);
  SWAP(d[26], d[30]);
  SWAP(d[27], d[31]);

  /* Stage 4: 16 comparators */
  SWAP(d[0], d[8]);
  SWAP(d[1], d[9]);
  SWAP(d[2], d[10]);
  SWAP(d[3], d[11]);
  SWAP(d[4], d[12]);
  SWAP(d[5], d[13]);
  SWAP(d[6], d[14]);
  SWAP(d[7], d[15]);
  SWAP(d[16], d[24]);
  SWAP(d[17], d[25]);
  SWAP(d[18], d[26]);
  SWAP(d[19], d[27]);
  SWAP(d[20], d[28]);
  SWAP(d[21], d[29]);
  SWAP(d[22], d[30]);
  SWAP(d[23], d[31]);

  /* Stage 5: 16 comparators */
  SWAP(d[0], d[16]);
  SWAP(d[1], d[8]);
  SWAP(d[2], d[4]);
  SWAP(d[3], d[12]);
  SWAP(d[5], d[10]);
  SWAP(d[6], d[9]);
  SWAP(d[7], d[14]);
  SWAP(d[11], d[13]);
  SWAP(d[15], d[31]);
  SWAP(d[17], d[24]);
  SWAP(d[18], d[20]);
  SWAP(d[19], d[28]);
  SWAP(d[21], d[26]);
  SWAP(d[22], d[25]);
  SWAP(d[23], d[30]);
  SWAP(d[27], d[29]);

  /* Stage 6: 14 comparators */
  SWAP(d[1], d[2]);
  SWAP(d[3], d[5]);
  SWAP(d[4], d[8]);
  SWAP(d[6], d[22]);
  SWAP(d[7], d[11]);
  SWAP(d[9], d[25]);
  SWAP(d[10], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[17], d[18]);
  SWAP(d[19], d[21]);
  SWAP(d[20], d[24]);
  SWAP(d[23], d[27]);
  SWAP(d[26], d[28]);
  SWAP(d[29], d[30]);

  /* Stage 7: 12 comparators */
  SWAP(d[1], d[17]);
  SWAP(d[2], d[18]);
  SWAP(d[3], d[19]);
  SWAP(d[4], d[20]);
  SWAP(d[5], d[10]);
  SWAP(d[7], d[23]);
  SWAP(d[8], d[24]);
  SWAP(d[11], d[27]);
  SWAP(d[12], d[28]);
  SWAP(d[13], d[29]);
  SWAP(d[14], d[30]);
  SWAP(d[21], d[26]);

  /* Stage 8: 12 comparators */
  SWAP(d[3], d[17]);
  SWAP(d[4], d[16]);
  SWAP(d[5], d[21]);
  SWAP(d[6], d[18]);
  SWAP(d[7], d[9]);
  SWAP(d[8], d[20]);
  SWAP(d[10], d[26]);
  SWAP(d[11], d[23]);
  SWAP(d[13], d[25]);
  SWAP(d[14], d[28]);
  SWAP(d[15], d[27]);
  SWAP(d[22], d[24]);

  /* Stage 9: 12 comparators */
  SWAP(d[1], d[4]);
  SWAP(d[3], d[8]);
  SWAP(d[5], d[16]);
  SWAP(d[7], d[17]);
  SWAP(d[9], d[21]);
  SWAP(d[10], d[22]);
  SWAP(d[11], d[19]);
  SWAP(d[12], d[20]);
  SWAP(d[14], d[24]);
  SWAP(d[15], d[26]);
  SWAP(d[23], d[28]);
  SWAP(d[27], d[30]);

  /* Stage 10: 10 comparators */
  SWAP(d[2], d[5]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[18]);
  SWAP(d[11], d[17]);
  SWAP(d[12], d[16]);
  SWAP(d[13], d[22]);
  SWAP(d[14], d[20]);
  SWAP(d[15], d[19]);
  SWAP(d[23], d[24]);
  SWAP(d[26], d[29]);

  /* Stage 11: 10 comparators */
  SWAP(d[2], d[4]);
  SWAP(d[6], d[12]);
  SWAP(d[9], d[16]);
  SWAP(d[10], d[11]);
  SWAP(d[13], d[17]);
  SWAP(d[14], d[18]);
  SWAP(d[15], d[22]);
  SWAP(d[19], d[25]);
  SWAP(d[20], d[21]);
  SWAP(d[27], d[29]);

  /* Stage 12: 10 comparators */
  SWAP(d[5], d[6]);
  SWAP(d[8], d[12]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[13]);
  SWAP(d[14], d[16]);
  SWAP(d[15], d[17]);
  SWAP(d[18], d[20]);
  SWAP(d[19], d[23]);
  SWAP(d[21], d[22]);
  SWAP(d[25], d[26]);

  /* Stage 13: 12 comparators */
  SWAP(d[3], d[5]);
  SWAP(d[6], d[7]);
  SWAP(d[8], d[9]);
  SWAP(d[10], d[12]);
  SWAP(d[11], d[14]);
  SWAP(d[13], d[16]);
  SWAP(d[15], d[18]);
  SWAP(d[17], d[20]);
  SWAP(d[19], d[21]);
  SWAP(d[22], d[23]);
  SWAP(d[24], d[25]);
  SWAP(d[26], d[28]);

  /* Stage 14: 13 comparators */
  SWAP(d[3], d[4]);
  SWAP(d[5], d[6]);
  SWAP(d[7], d[8]);
  SWAP(d[9], d[10]);
  SWAP(d[11], d[12]);
  SWAP(d[13], d[14]);
  SWAP(d[15], d[16]);
  SWAP(d[17], d[18]);
  SWAP(d[19], d[20]);
  SWAP(d[21], d[22]);
  SWAP(d[23], d[24]);
  SWAP(d[25], d[26]);
  SWAP(d[27], d[28]);
}

/* Efficient merge function for combining two sorted regions */
static inline void merge_sorted_regions(double *d, int left, int mid, int right)
{
  int n1 = mid - left + 1;
  int n2 = right - mid;

  /* Use stack allocation for small merges, malloc for large */
  double temp_buffer[128];
  double *temp = (n1 + n2 <= 128) ? temp_buffer : (double *)malloc((n1 + n2) * sizeof(double));

  /* Copy data to temp buffer */
  for (int i = 0; i < n1; i++)
    temp[i] = d[left + i];
  for (int i = 0; i < n2; i++)
    temp[n1 + i] = d[mid + 1 + i];

  /* Merge back to original array */
  int i = 0, j = n1, k = left;
  while (i < n1 && j < n1 + n2)
  {
    if (temp[i] <= temp[j])
      d[k++] = temp[i++];
    else
      d[k++] = temp[j++];
  }

  /* Copy remaining elements */
  while (i < n1)
    d[k++] = temp[i++];
  while (j < n1 + n2)
    d[k++] = temp[j++];

  /* Free if we malloc'd */
  if (n1 + n2 > 128)
    free(temp);
}

/* Apply the best-fitting sorting network to a range of elements */
static inline void sort_with_best_network(double *d, int size)
{
  /* Use the largest optimal network that fits */
  if (size >= 32)
    sort32(d);
  else if (size >= 31)
    sort31(d);
  else if (size >= 30)
    sort30(d);
  else if (size >= 29)
    sort29(d);
  else if (size >= 28)
    sort28(d);
  else if (size >= 27)
    sort27b(d);
  else if (size >= 26)
    sort26(d);
  else if (size >= 25)
    sort25b(d);
  else if (size >= 24)
    sort24(d);
  else if (size >= 23)
    sort23(d);
  else if (size >= 22)
    sort22(d);
  else if (size >= 21)
    sort21(d);
  else if (size >= 20)
    sort20(d);
  else if (size >= 19)
    sort19(d);
  else if (size >= 18)
    sort18(d);
  else if (size >= 17)
    sort17(d);
  else if (size >= 16)
    sort16(d);
  else if (size >= 15)
    sort15(d);
  else if (size >= 14)
    sort14(d);
  else if (size >= 13)
    sort13(d);
  else if (size >= 12)
    sort12(d);
  else if (size >= 11)
    sort11(d);
  else if (size >= 10)
    sort10(d);
  else if (size >= 9)
    sort9(d);
  else if (size >= 8)
    sort8(d);
  else if (size >= 7)
    sort7(d);
  else if (size >= 6)
    sort6(d);
  else if (size >= 5)
    sort5(d);
  else if (size >= 4)
    sort4(d);
  else if (size >= 3)
    sort3(d);
  else if (size == 2)
    SWAP(d[0], d[1]);
  /* size < 2 is already sorted */
}

/* Optimized hybrid sort: partition into optimal networks, then merge efficiently */
#define HYBRID_SORT_OPTIMIZED(N)                                        \
  static inline void sort##N(double *d)                                 \
  {                                                                     \
    /* Partition N into optimal network sizes and sort each */          \
    int pos = 0;                                                        \
    while (pos < N)                                                     \
    {                                                                   \
      int remaining = N - pos;                                          \
      int chunk_size = (remaining >= 32) ? 32 : remaining;              \
      sort_with_best_network(&d[pos], chunk_size);                      \
      pos += chunk_size;                                                \
    }                                                                   \
    /* Merge sorted chunks pairwise until fully sorted */               \
    for (int merge_size = 32; merge_size < N; merge_size *= 2)          \
    {                                                                   \
      for (int left = 0; left < N - merge_size; left += merge_size * 2) \
      {                                                                 \
        int mid = left + merge_size - 1;                                \
        int right = (left + merge_size * 2 - 1 < N - 1)                 \
                        ? left + merge_size * 2 - 1                     \
                        : N - 1;                                        \
        if (mid < right)                                                \
          merge_sorted_regions(d, left, mid, right);                    \
      }                                                                 \
    }                                                                   \
  }

/* Generate optimized hybrid sorts for N=33-119 */
/* These use optimal network partitioning + efficient merging instead of insertion sort */
HYBRID_SORT_OPTIMIZED(33)
HYBRID_SORT_OPTIMIZED(34)
HYBRID_SORT_OPTIMIZED(35)
HYBRID_SORT_OPTIMIZED(36)
HYBRID_SORT_OPTIMIZED(37)
HYBRID_SORT_OPTIMIZED(38)
HYBRID_SORT_OPTIMIZED(39)
HYBRID_SORT_OPTIMIZED(40)
HYBRID_SORT_OPTIMIZED(41)
HYBRID_SORT_OPTIMIZED(42)
HYBRID_SORT_OPTIMIZED(43)
HYBRID_SORT_OPTIMIZED(44)
HYBRID_SORT_OPTIMIZED(45)
HYBRID_SORT_OPTIMIZED(46)
HYBRID_SORT_OPTIMIZED(47)
HYBRID_SORT_OPTIMIZED(48)
HYBRID_SORT_OPTIMIZED(49)
HYBRID_SORT_OPTIMIZED(50)
HYBRID_SORT_OPTIMIZED(51)
HYBRID_SORT_OPTIMIZED(52)
HYBRID_SORT_OPTIMIZED(53)
HYBRID_SORT_OPTIMIZED(54)
HYBRID_SORT_OPTIMIZED(55)
HYBRID_SORT_OPTIMIZED(56)
HYBRID_SORT_OPTIMIZED(57)
HYBRID_SORT_OPTIMIZED(58)
HYBRID_SORT_OPTIMIZED(59)
HYBRID_SORT_OPTIMIZED(60)
HYBRID_SORT_OPTIMIZED(61)
HYBRID_SORT_OPTIMIZED(62)
HYBRID_SORT_OPTIMIZED(63)
HYBRID_SORT_OPTIMIZED(64)
HYBRID_SORT_OPTIMIZED(65)
HYBRID_SORT_OPTIMIZED(66)
HYBRID_SORT_OPTIMIZED(67)
HYBRID_SORT_OPTIMIZED(68)
HYBRID_SORT_OPTIMIZED(69)
HYBRID_SORT_OPTIMIZED(70)
HYBRID_SORT_OPTIMIZED(71)
HYBRID_SORT_OPTIMIZED(72)
HYBRID_SORT_OPTIMIZED(73)
HYBRID_SORT_OPTIMIZED(74)
HYBRID_SORT_OPTIMIZED(75)
HYBRID_SORT_OPTIMIZED(76)
HYBRID_SORT_OPTIMIZED(77)
HYBRID_SORT_OPTIMIZED(78)
HYBRID_SORT_OPTIMIZED(79)
HYBRID_SORT_OPTIMIZED(80)
HYBRID_SORT_OPTIMIZED(81)
HYBRID_SORT_OPTIMIZED(82)
HYBRID_SORT_OPTIMIZED(83)
HYBRID_SORT_OPTIMIZED(84)
HYBRID_SORT_OPTIMIZED(85)
HYBRID_SORT_OPTIMIZED(86)
HYBRID_SORT_OPTIMIZED(87)
HYBRID_SORT_OPTIMIZED(88)
HYBRID_SORT_OPTIMIZED(89)
HYBRID_SORT_OPTIMIZED(90)
HYBRID_SORT_OPTIMIZED(91)
HYBRID_SORT_OPTIMIZED(92)
HYBRID_SORT_OPTIMIZED(93)
HYBRID_SORT_OPTIMIZED(94)
HYBRID_SORT_OPTIMIZED(95)
HYBRID_SORT_OPTIMIZED(96)
HYBRID_SORT_OPTIMIZED(97)
HYBRID_SORT_OPTIMIZED(98)
HYBRID_SORT_OPTIMIZED(99)
HYBRID_SORT_OPTIMIZED(100)
HYBRID_SORT_OPTIMIZED(101)
HYBRID_SORT_OPTIMIZED(102)
HYBRID_SORT_OPTIMIZED(103)
HYBRID_SORT_OPTIMIZED(104)
HYBRID_SORT_OPTIMIZED(105)
HYBRID_SORT_OPTIMIZED(106)
HYBRID_SORT_OPTIMIZED(107)
HYBRID_SORT_OPTIMIZED(108)
HYBRID_SORT_OPTIMIZED(109)
HYBRID_SORT_OPTIMIZED(110)
HYBRID_SORT_OPTIMIZED(111)
HYBRID_SORT_OPTIMIZED(112)
HYBRID_SORT_OPTIMIZED(113)
HYBRID_SORT_OPTIMIZED(114)
HYBRID_SORT_OPTIMIZED(115)
HYBRID_SORT_OPTIMIZED(116)
HYBRID_SORT_OPTIMIZED(117)
HYBRID_SORT_OPTIMIZED(118)
HYBRID_SORT_OPTIMIZED(119)

/* Optimized hybrid sort for N=120-125 */
HYBRID_SORT_OPTIMIZED(120)

HYBRID_SORT_OPTIMIZED(121)
HYBRID_SORT_OPTIMIZED(122)
HYBRID_SORT_OPTIMIZED(123)
HYBRID_SORT_OPTIMIZED(124)
HYBRID_SORT_OPTIMIZED(125)
